### ISSUE TITLE
ERROR: duplicate files

### ISSUE THREAD

**Issue by rohit12043-zz** [syberia-project/platform_vendor_syberia#3]
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/rohit/syberia/out/target/product/a6000/system/etc/mkshrc'
ninja: error: /home/rohit/syberia/out/soong/build.ninja:392124: multiple rules generate /home/rohit/syberia/out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/aapt2/vendor/syberia/overlay/common/frameworks/base/core/res/res/drawable-xhdpi_default_wallpaper.png.flat [-w dupbuild=err]

18:07:17 ninja failed with: exit status 1
build/make/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1

real	1m12.170s
user	2m14.454s
sys	0m10.976s

'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/rohit/syberia/out/target/product/a6000/system/etc/mkshrc'
ninja: error: /home/rohit/syberia/out/soong/build.ninja:392116: multiple rules generate /home/rohit/syberia/out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/aapt2/vendor/syberia/overlay/common/frameworks/base/core/res/res/values_colors.arsc.flat [-w dupbuild=err]

18:11:26 ninja failed with: exit status 1
build/make/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1

real	1m20.008s
user	2m20.726s
sys	0m11.689s

build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/rohit/syberia/out/target/product/a6000/system/etc/mkshrc'
ninja: error: /home/rohit/syberia/out/soong/build.ninja:392100: multiple rules generate /home/rohit/syberia/out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/aapt2/vendor/syberia/overlay/common/frameworks/base/core/res/res/xml_config_webview_packages.xml.flat [-w dupbuild=err]

18:15:18 ninja failed with: exit status 1
build/make/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1

real	1m17.034s
user	2m17.038s
sys	0m11.681s

**Comment by DennySPB** [comment]
Not ROM issue. Enforce RRO on framework-res in device tree.
